# Generated by Django 4.1 on 2022-09-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_alter_movie_premier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='director',
        ),
    ]
