# Generated by Django 4.1 on 2022-09-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_rename_author_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.movie'),
        ),
    ]
