# Generated by Django 4.1 on 2022-09-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_author_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='movies',
        ),
        migrations.AddField(
            model_name='author',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='cine.movie'),
        ),
    ]
