# Generated by Django 4.1 on 2022-09-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0006_remove_author_movies_author_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='movies',
            field=models.ManyToManyField(to='cine.movie'),
        ),
    ]
